application: your-app-id-goes-here
version: v1
runtime: python27
api_version: 1
threadsafe: yes

env_variables:
  BUCKET: 'your-bucket-name-goes-here'

handlers:
- url: /blobstore.*
  script: blobstore.app

- url: /.*
  script: main.app
